[project]
name = "number-4"
version = "0.1.0"
description = "Vector DB with Cosine Similarity"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "coverage>=7.10.4",
    "pytest-asyncio>=1.1.0",
    "pytest>=8.4.1",
]
